on: 
  workflow_dispatch:
  push:
    branches: 
      - development
name: Update Development Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
  
    - name: Use Node.js 16.0
      uses: actions/setup-node@v1
      with:
        node-version: '16'
        
    - name: Build Project
      run: |
        npm install
        npm run build
  
    - name: List output files
      run: find build/ -print

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_DEVELOPMENT_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: dev.findagravemiddleborough.ml/htdocs/
        local-dir: build/